Piecyk/Piecyk/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Piecyk.Models;
using Microsoft.AspNet.Identity;

namespace Piecyk.Controllers
{
    public class CarController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Car
        [Authorize]
        public ActionResult Index(bool? id)
        {
            string ids = User.Identity.GetUserId();
            var carModels = db.CarModels.ToList();

            if (id != null)
                carModels = db.CarModels.Where(p => p.UserID == ids).ToList();

            foreach (var car in carModels)
                car.UserInfo = db.UserInfoModels.Where(p => p.ID == car.UserID).SingleOrDefault();

            return View(carModels);
        }

        // GET: Ads
        public ActionResult Ads()
        {
            //string ids = User.Identity.GetUserId();
            var carModels = db.CarModels.Where(p => p.Status == true).ToList();

            foreach (var car in carModels)
                car.UserInfo = db.UserInfoModels.Where(p => p.ID == car.UserID).SingleOrDefault();

            return View(carModels);
        }

        // GET: Wystaw
        [Authorize]
        public ActionResult Check(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModels carModels = db.CarModels.Find(id);
            if (carModels == null)
            {
                return HttpNotFound();
            }
            string adr = "Edit/" + id.ToString();
            if (carModels.SalesAmount == null)
            {
                return RedirectToAction(adr);
            }

            carModels.Status = true;
            db.Entry(carModels).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Anuluj
        [Authorize]
        public ActionResult Checked(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModels carModels = db.CarModels.Find(id);
            if (carModels == null)
            {
                return HttpNotFound();
            }

            carModels.Status = false;
            db.Entry(carModels).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Buy
        [Authorize]
        public ActionResult Buy(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModels carModels = db.CarModels.Find(id);
            if (carModels == null)
            {
                return HttpNotFound();
            }

            string ids = User.Identity.GetUserId();
            carModels.UserID = ids;

            carModels.PurchaseAmount = (double)carModels.SalesAmount;
            carModels.SalesAmount = null;
            carModels.Status = false;

            db.Entry(carModels).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Car/Details/5
   
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModels carModels = db.CarModels.Find(id);
            if (carModels == null)
            {
                return HttpNotFound();
            }
            carModels.UserInfo = db.UserInfoModels.Where(p => p.ID == carModels.UserID).SingleOrDefault();
            
            carModels.Tuning = db.TuningModels.Where(p => p.CarID == id.ToString()).ToList();

            return View(carModels);
        }

        // GET: Car/Create
        [Authorize]
        public ActionResult Create()
        {
            var context = new ApplicationDbContext();
            string id = User.Identity.GetUserId();
            if (context.UserInfoModels.Where(u => u.ID == id).Count() > 0)
            {
                return View();
            }

            return RedirectToAction("../UserInfo/Create");
        }

        // POST: Car/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "ID,Mark,Model,Year,VIN,Name,Picture,PurchaseDate,PurchaseAmount,SalesAmount")] CarModels carModels)
        {
            carModels.UserID = User.Identity.GetUserId();
            carModels.Status = false;

            if (ModelState.IsValid)
            {
                db.CarModels.Add(carModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(carModels);
        }

        // GET: Car/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModels carModels = db.CarModels.Find(id);
            if (carModels == null)
            {
                return HttpNotFound();
            }
            return View(carModels);
        }

        // POST: Car/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ID,Mark,Model,Year,VIN,Name,Picture,PurchaseDate,PurchaseAmount,SalesAmount")] CarModels carModels)
        {
            carModels.UserID = User.Identity.GetUserId();
            carModels.Status = false;

            if (ModelState.IsValid)
            {
                db.Entry(carModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carModels);
        }

        // GET: Car/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarModels carModels = db.CarModels.Find(id);
            if (carModels == null)
            {
                return HttpNotFound();
            }
            return View(carModels);
        }

        // POST: Car/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            CarModels carModels = db.CarModels.Find(id);
            db.CarModels.Remove(carModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Piecyk/Piecyk/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Piecyk.Models;
using Microsoft.AspNet.Identity;

namespace Piecyk.Controllers
{
    public class UserInfoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserInfo
        [Authorize]
        public ActionResult Index()
        {
            return View(db.UserInfoModels.ToList());
        }

        // GET: UserInfo/Details/5
        [Authorize]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfoModels userInfoModels = db.UserInfoModels.Find(id);
            if (userInfoModels == null)
            {
                return HttpNotFound();
            }

            var carModels = db.CarModels.Where(p => p.UserID == id).ToList();

            userInfoModels.Car = carModels;

            return View(userInfoModels);
        }

        // GET: UserInfo/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserInfo/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "FirstName,LastName,PhoneNo")] UserInfoModels userInfoModels)
        {
            userInfoModels.ID = User.Identity.GetUserId();
            userInfoModels.Email = User.Identity.Name;
            if (ModelState.IsValid)
            {
                db.UserInfoModels.Add(userInfoModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userInfoModels);
        }

        // GET: UserInfo/Edit/5
        [Authorize]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfoModels userInfoModels = db.UserInfoModels.Find(id);
            if (userInfoModels == null)
            {
                return HttpNotFound();
            }
            if (id != User.Identity.GetUserId())
            {
                return HttpNotFound();
            }

            return View(userInfoModels);
        }

        // POST: UserInfo/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,PhoneNo")] UserInfoModels userInfoModels)
        {
            userInfoModels.ID = User.Identity.GetUserId();
            userInfoModels.Email = User.Identity.Name;
            if (ModelState.IsValid)
            {
                db.Entry(userInfoModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userInfoModels);
        }

        // GET: UserInfo/Delete/5
        [Authorize]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfoModels userInfoModels = db.UserInfoModels.Find(id);
            if (userInfoModels == null)
            {
                return HttpNotFound();
            }
            return View(userInfoModels);
        }

        // POST: UserInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(string id)
        {
            UserInfoModels userInfoModels = db.UserInfoModels.Find(id);
            db.UserInfoModels.Remove(userInfoModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Piecyk/Piecyk/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — wszelkie prawa zastrzeżone. A. Piecyk </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"> PiecykSite </a>
        <button class="navbar-toggler" aria-expanded="false" aria-controls="navbarColor03" aria-label="Toggle navigation" type="button" data-toggle="collapse" data-target="#navbarColor03">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Strona Główna", "Index", "Home", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Kontakt", "Contact", "Home", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Informacje", "About", "Home", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Ogłoszenia", "Ads", "Car", routeValues: null, htmlAttributes: new { @class = "nav-link" })
                </li>
                @if (Request.IsAuthenticated)
                {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="download" aria-expanded="false" href="#" data-toggle="dropdown">Bazy <span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="download">
                        @Html.ActionLink("Właściciele", "Index", "UserInfo", routeValues: null, htmlAttributes: new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Samochody", "Index", "Car", routeValues: null, htmlAttributes: new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Tuning", "Index", "Tuning", routeValues: null, htmlAttributes: new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="download" aria-expanded="false" href="#" data-toggle="dropdown">Moje <span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="download">
                        @Html.ActionLink("Samochody", "Index", "Car", new { id = true }, htmlAttributes: new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Tuning", "Index", "Tuning", new { id = true }, htmlAttributes: new { @class = "dropdown-item" })
                    </div>
                </li>
                }
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year — fajna aplikacja na zaliczenie przedmiotu ASP.NET.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://bootswatch.com/_vendor/popper.js/dist/umd/popper.min.js"></script>
    <script src="https://bootswatch.com/_vendor/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>